this doc uses 'PlantUML integration' in intellij
see https://github.com/esteinberg/plantuml4idea

@startuml

Team -> Tracker: (PM) create & refine Feature
Team -> Team: (PM/Dev) Iteration Planning Meeting estimate and start story current sprint
Team -> Git: (Dev) Implement story in feature branch
Team -> Git: (Dev) Commit to develop branch (Peer Review Process)
Git -> Concourse : Trigger CI build //Development//, Run Unit Testing
Concourse -> CloudFoundry: Deploy to Dev Space
Concourse -> Tracker: Finish the story
Team -> CloudFoundry: (PM) Validates the feature
Team -> Tracker: (PM) Accepts Story
Team -> Git: (Dev/PM) Prepare Release Candidate
Git -> Concourse: Trigger CI Build //Staging//, create release candidate release branch
Concourse -> CloudFoundry: Deploy to Staging Space
Concourse -> Concourse: Run Integration Testing
Team -> CloudFoundry: (Client/QA) Validates the feature
Team -> Tracker: (QA) Open bug fixes if necessary, Marks the Feature ready for Release (Notes)
Team -> Concourse: (Client) Trigger merge Release to Master branch
Concourse -> Git: Tag Release and Bump version
Git -> Concourse: Trigger CI build //Production//
Concourse -> CloudFoundry: Blue Green Deployment to Production Space
Team -> CloudFoundry: (Client) Validates the release, switch blue and green
Team -> Tracker: (Client) Marks Release successful

@enduml